@startuml
left to right direction

skinparam handwritten false

skinparam usecase {
  BackgroundColor #FBF5C3
  BorderColor #000000
}

skinparam rectangle {
  BorderColor #000000
}

' ==== Ator ====
actor Leitor as L

' ==== Pacote ====
rectangle "Avaliar Livros – LitNet" {

    usecase "Avaliar Livro" as UC_Avaliar
    usecase "Armazenar Avaliação" as UC_Armazenar
    usecase "Publicar Avaliação" as UC_Publicar

}

' ==== Ligações ====
L --> UC_Avaliar
L --> UC_Publicar

' ==== Include / Extend ====
UC_Avaliar --> UC_Armazenar : <<include>>
UC_Avaliar <.. UC_Publicar : <<extend>>
@enduml